# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34fedc173a477995a20ee3672dddec347607f449309b7f2adeec90cfb305a4bd0de2f581e34a190a045519daec92207305ef3944dce2211dbce7ee9b04409876

test:
  secret_key_base: 45c59e03f634d343352c8e510547c586c8201561ec259e55dc15a225cc3c87f6c4b4838b2579d7b9d4d5ea48db14a01d4f3e955db7e44f8a6ac58d6c73fe4304

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
